### ISSUE TITLE
[Suggestion] Add GitHub Issue Template for the Project

### ISSUE THREAD

**Issue by manulthanura** [sunny7899/html-templates#12]
I noticed that this repository does not have a GitHub issue template. Adding an issue template will help contributors follow a consistent structure when reporting bugs, suggesting features, or asking questions. It can streamline communication and make issues easier to manage.

I recommend adding different templates for:
- Bug reports
- Feature requests
- General questions

Would love to hear your thoughts on this and I'm ready for development.

@sunny7899

**Comment by sunny7899** [comment]
Great Go ahead @manulthanura
